### ISSUE TITLE
Error: Application entry file "build\electron.js" in the "D:\project\dist\win-unpacked\resources\app.asar" does not exist

### ISSUE THREAD

**Issue by razasaleem450** [popupbits/react-electron#1]
**On yarn dev electron working fine but when i run "yarn run ebuild" i will get this error** 

![node js command prompt 2018-12-18 12 40 00](https://user-images.githubusercontent.com/38685304/50139202-c8f63380-02c2-11e9-914d-3144435ee897.png)
Error: Application entry file "build\electron.js" in the "D:\xampp\htdocs\nextech-admin-app\admin\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\out\asar\asarFileChecker.js:44:14)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at _checkFileInArchive (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:36:17)
    at checkFileInArchive (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\out\asar\asarFileChecker.js:40:30)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.checkFileInPackage (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:406:110)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at WinPackager.sanityCheckPackage (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:446:92)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:396:24)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\graceful-fs\graceful-fs.js:111:16
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:335:133)
    at D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\xampp\htdocs\nextech-admin-app\admin\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lohanidamodar** [comment]
This in an windows related issue...I haven't tested with development on windows machine....
Check out this issue in electron-builder it might help you
https://github.com/electron-userland/electron-builder/issues/2404

**Comment by lohanidamodar** [comment]
As i did not get any further query, I am closing this issue.

**Comment by EdmarPereira** [comment]
I have a similar problem with this, for me first I yarn build and after this yarn electron-builder -m
